markdown: kramdown
baseurl: /jekyll-ookami
url: http://dchantzis.github.io/jekyll-ookami/
title: John Smith
subtitle: Professional Title
description: Portfolio
author: John Smith
e-mail: demo@demoemail.smth
phone: +440011001100
exclude: ['README.md', '.gitignore']
permalink: pretty
social:
  - provider: linkedin
    account-id:
  - provider: github
    account-id:
include-analytics-tracking: false
google-api-key: AIzaSyDRzuGOC7F2MLIzQaJAeYWjKoZq3g3Boo4
analytics :
  provider : google
  google :
    tracking_id:
google-maps:
  latitude: 36.6190943
  longitude: 24.9065212
  zoom: 12
collections:
  projects:
    output: true
    permalink: /work/:path/
  resume:
    output: true
    permalink: /resume/:path/
  tags:
    output: true
    permalink: /tag/:path/
gems: [
    jekyll-paginate,
    jekyll/tagging,
    jekyll-tagging-related_posts
  ]
paginate: 5
paginate_path: "/news/page:num/"
contact-info:
  name: John Smith
  job-title: Job Title
  e-mail: demo@demoemail.smth
  phone: +44 (0) 0011001100
  website-url: www.website-url.com
  address:
      street: Street
      locality: Locality
      region: Region
      country: Country
      postal-code: Post Code
enablePostsTimeToRead: true
disqus:
  comments: true
  url: demodchantzis.disqus.com
instagram-feed: true
display-social-media-share-buttons: true
single-page-layout: true
