markdown: kramdown
baseurl: /jekyll-ookami
url:
title: Dimitrios Chantzis
subtitle: Informatics Engineer and Web Developer based in Brighton, UK
description: Portfolio
author: Dimitrios Chantzis
e-mail: info@dimitrioschantzis.com
phone: +447511719938
exclude: ['README.md', '.gitignore']
permalink: pretty
social:
  - provider: linkedin
    account-id: dchantzis
  - provider: github
    account-id: dchantzis
include-analytics-tracking: true
google-api-key: AIzaSyDXBadFOiO-Fi3je-knf3Jwbo_xNE1twXc
analytics :
  provider : google
  google :
    tracking_id: 'UA-76614555-1'
google-maps:
  latitude: 50.823196
  longitude: -0.137262
  zoom: 15
collections:
  projects:
    output: true
    permalink: /work/:path/
  resume:
    output: true
    permalink: /resume/:path/
  tags:
    output: true
    permalink: /tag/:path/
gems: [
    jekyll-paginate,
    jekyll/tagging,
    jekyll-tagging-related_posts
  ]
paginate: 5
paginate_path: "/news/page:num/"
contact-info:
  name: Dimitrios Chantzis
  job-title: Informatics Engineer
  e-mail: info@dimitrioschantzis.com
  phone: +44 (0) 7511719938
  website-url: www.dimitrioschantzis.com
  address:
      street:
      locality: Norfolk square
      region: Brighton
      country: U.K.
      postal-code: BN1 2QA
enableSiteSearch: false
enablePostsTimeToRead: true
disqus:
  comments: true
  url: demodchantzis.disqus.com
instagram-feed: true
display-social-media-share-buttons: true
single-page-layout: false
